controller_list:
  - name: fake_franka_controller
    type: $(arg fake_execution_type)
    joints:
      - franka_joint1
      - franka_joint2
      - franka_joint3
      - franka_joint4
      - franka_joint5
      - franka_joint6
      - franka_joint7
  - name: fake_franko_controller
    type: $(arg fake_execution_type)
    joints:
      - franko_joint1
      - franko_joint2
      - franko_joint3
      - franko_joint4
      - franko_joint5
      - franko_joint6
      - franko_joint7
  - name: fake_combined_controller
    type: $(arg fake_execution_type)
    joints:
      - franko_joint1
      - franko_joint2
      - franko_joint3
      - franko_joint4
      - franko_joint5
      - franko_joint6
      - franko_joint7
      - franka_joint1
      - franka_joint2
      - franka_joint3
      - franka_joint4
      - franka_joint5
      - franka_joint6
      - franka_joint7
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - franka_finger_joint1
      - franka_finger_joint2
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - franko_finger_joint1
      - franko_finger_joint2
initial:  # Define initial robot poses per group
  - group: franka
    pose: ready
  - group: franko
    pose: ready
  - group: left_hand
    pose: close
  - group: right_hand
    pose: close