joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

combined_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - franko_joint1
        - franko_joint2
        - franko_joint3
        - franko_joint4
        - franko_joint5
        - franko_joint6
        - franko_joint7
        - franka_joint1
        - franka_joint2
        - franka_joint3
        - franka_joint4
        - franka_joint5
        - franka_joint6
        - franka_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        franko_joint1: {trajectory: 0.1, goal: 0.1}
        franko_joint2: {trajectory: 0.1, goal: 0.1}
        franko_joint3: {trajectory: 0.1, goal: 0.1}
        franko_joint4: {trajectory: 0.1, goal: 0.1}
        franko_joint5: {trajectory: 0.1, goal: 0.1}
        franko_joint6: {trajectory: 0.1, goal: 0.1}
        franko_joint7: {trajectory: 0.1, goal: 0.1}
        franka_joint1: {trajectory: 0.1, goal: 0.1}
        franka_joint2: {trajectory: 0.1, goal: 0.1}
        franka_joint3: {trajectory: 0.1, goal: 0.1}
        franka_joint4: {trajectory: 0.1, goal: 0.1}
        franka_joint5: {trajectory: 0.1, goal: 0.1}
        franka_joint6: {trajectory: 0.1, goal: 0.1}
        franka_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
        franko_joint1:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint2:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint3:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint4:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint5:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint6:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint7:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint1:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint2:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint3:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint4:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint5:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint6:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint7:
            p: 100
            d: 1
            i: 1
            i_clamp: 1

franko_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - franko_joint1
        - franko_joint2
        - franko_joint3
        - franko_joint4
        - franko_joint5
        - franko_joint6
        - franko_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        franko_joint1: {trajectory: 0.1, goal: 0.1}
        franko_joint2: {trajectory: 0.1, goal: 0.1}
        franko_joint3: {trajectory: 0.1, goal: 0.1}
        franko_joint4: {trajectory: 0.1, goal: 0.1}
        franko_joint5: {trajectory: 0.1, goal: 0.1}
        franko_joint6: {trajectory: 0.1, goal: 0.1}
        franko_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
        franko_joint1:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint2:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint3:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint4:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint5:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint6:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franko_joint7:
            p: 100
            d: 1
            i: 1
            i_clamp: 1

franka_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - franka_joint1
        - franka_joint2
        - franka_joint3
        - franka_joint4
        - franka_joint5
        - franka_joint6
        - franka_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        franka_joint1: {trajectory: 0.1, goal: 0.1}
        franka_joint2: {trajectory: 0.1, goal: 0.1}
        franka_joint3: {trajectory: 0.1, goal: 0.1}
        franka_joint4: {trajectory: 0.1, goal: 0.1}
        franka_joint5: {trajectory: 0.1, goal: 0.1}
        franka_joint6: {trajectory: 0.1, goal: 0.1}
        franka_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
        franka_joint1:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint2:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint3:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint4:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint5:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint6:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        franka_joint7:
            p: 100
            d: 1
            i: 1
            i_clamp: 1

#notice that the grippers joint2 mimics joint1
#this is why it is not listed under the hand controllers
right_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - franko_finger_joint1
        - franko_finger_joint2
    gains:
        franko_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
        franko_finger_joint2:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
    constraints:
        goal_time: 0.5                   # Override default
        stopped_velocity_tolerance: 0.02 # Override default

left_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - franka_finger_joint1
        - franka_finger_joint2
    gains:
        franka_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
        franka_finger_joint2:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
    constraints:
        goal_time: 0.5                   # Override default
        stopped_velocity_tolerance: 0.02 # Override default