controller_list:
  - name: franko_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - franko_joint1
      - franko_joint2
      - franko_joint3
      - franko_joint4
      - franko_joint5
      - franko_joint6
      - franko_joint7
  - name: franka_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - franka_joint1
      - franka_joint2
      - franka_joint3
      - franka_joint4
      - franka_joint5
      - franka_joint6
      - franka_joint7
  - name: combined_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - franko_joint1
      - franko_joint2
      - franko_joint3
      - franko_joint4
      - franko_joint5
      - franko_joint6
      - franko_joint7
      - franka_joint1
      - franka_joint2
      - franka_joint3
      - franka_joint4
      - franka_joint5
      - franka_joint6
      - franka_joint7

  #notice that the gripper's joint2 mimics joint1
  #this is why it is not listed under the hand controllers

  - name: right_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - franko_finger_joint1
      - franko_finger_joint2

  - name: left_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - franka_finger_joint1
      - franka_finger_joint2